# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# hospital_network_model.py
# Created on: 2015-02-04 13:26:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("Network")


# Local variables:
roads_ND = "E:\\Lab_2\\Data\\SvcAreas.gdb\\roads\\roads_ND"
CriticalHospitals = "E:\\Lab_2\\Data\\SvcAreas.gdb\\roads\\CriticalHospitals"
Polygons = "Hospital_Service_Areas\\Polygons"
MOplaces = "MOplaces"
Polygons__2_ = "Hospital_Service_Areas\\Polygons"
Hospital_Service_Areas = "Hospital_Service_Areas"
Hospital_Service_Areas__2_ = "Hospital_Service_Areas"
HospitalServiceZones = "E:\\Lab_2\\Data\\SvcAreas.gdb\\roads\\HospitalServiceZones"
MOplaces__2_ = "MOplaces"
ServedMOplaces = "E:\\Lab_2\\Data\\SvcAreas.gdb\\roads\\ServedMOplaces"
MO_Places_statistics = "E:\\Lab_2\\Data\\SvcAreas.gdb\\MO_Places_statistics"

# Process: Make Service Area Layer
arcpy.MakeServiceAreaLayer_na(roads_ND, "Hospital_Service_Areas", "traveltime", "TRAVEL_FROM", ".25", "SIMPLE_POLYS", "MERGE", "RINGS", "NO_LINES", "OVERLAP", "NO_SPLIT", "", "", "ALLOW_UTURNS", "", "NO_TRIM_POLYS", "100 Meters", "NO_LINES_SOURCE_FIELDS", "NO_HIERARCHY", "")

# Process: Add Locations
arcpy.AddLocations_na(Hospital_Service_Areas, "Facilities", CriticalHospitals, "Name Address #", "5000 Meters", "", "MORds SHAPE;roads_ND_Junctions NONE", "MATCH_TO_CLOSEST", "APPEND", "NO_SNAP", "5 Meters", "INCLUDE", "MORds #;roads_ND_Junctions #")

# Process: Solve
arcpy.Solve_na(Hospital_Service_Areas__2_, "SKIP", "TERMINATE", "")

# Process: Copy Features
arcpy.CopyFeatures_management(Polygons, HospitalServiceZones, "", "0", "0", "0")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(MOplaces, "COMPLETELY_WITHIN", Polygons__2_, "", "NEW_SELECTION")

# Process: Copy Features (2)
arcpy.CopyFeatures_management(MOplaces__2_, ServedMOplaces, "", "0", "0", "0")

# Process: Summary Statistics
arcpy.Statistics_analysis(MOplaces__2_, MO_Places_statistics, "POP90 SUM;POP00 SUM", "")

